title: Agreement measures for spatio-temporal models with applications toimage processing.
description: Fondecyt - Anid project Nº 1230012.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
